name: Test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 19

      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: Run Tests
        run: |
          npm run test
